name: MDM
use_tb_logger: true
model: rrdb
distortion: sr
scale: 3
pca_matrix_path: ../Your pca_matrix_path


gpu_ids: [2]

degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 2.0
  rate_iso: 1.0
  random_disturb: false


datasets:
  train:
    name: MRItrain
    mode: LQGTker
    dataroot_GT: ../GT
    dataroot_LQ: ../LQ
    use_shuffle: true
    n_workers: 8
    batch_size: 64
    GT_size:  512
    LR_size: 16
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: MRIval
    mode: LQGT
    dataroot_GT: ../GT
    dataroot_LQ: ../LQ

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

train:
  lr_G: !!float 4e-4
  lr_E: !!float 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99

  niter: 500000
  warmup_iter: -1
  lr_steps: [100000, 400000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 2e3


logger:
  print_freq: 2000
  save_checkpoint_freq: !!float 1e6
