name: DDSRx4_setting1
use_tb_logger: true
model: blind
distortion: sr
scale: 6



rrdb_ckpt: ../your rrdbpth


gpu_ids: [2]


datasets:
  train:
    name: MRItrain
    mode: LQGTker
    dataroot_GT: ../GT
    dataroot_LQ: ../LQ


    use_shuffle: true
    n_workers: 8
    batch_size: 16
    GT_size: 256
    LR_size: 16
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: MRIval
    mode: LQGT

    dataroot_GT: ../GT
    dataroot_LQ: ../LQ


path:
  pretrain_model_G: ~
  strict_load: false
  resume_state: ~

train:
  lr: !!float 2e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99

  niter: 90000
  warmup_iter: -1
  lr_steps: 100000

  lr_gamma: 0.5
  eta_min: !!float 1e-7 

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 2e3

logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1e5
